markdown: kramdown
exclude: ['README.md']
permalink: /blog/:year/:month/:day/:title
baseurl: /stat
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
gem "github-pages", group: :jekyll_plugins